CREATE TABLE UN_ENCULER_D_UTILISATEUR(
   Id_UN_ENCULER_D_UTILISATEUR INT AUTO_INCREMENT,
   SON_PTN_DE_NOM VARCHAR(255),
   PRIMARY KEY(Id_UN_ENCULER_D_UTILISATEUR)
);

CREATE TABLE label(
   Id_label INT AUTO_INCREMENT,
   PRIMARY KEY(Id_label)
);

CREATE TABLE disque(
   Id_disque INT AUTO_INCREMENT,
   titre VARCHAR(255),
   Artiste VARCHAR(255),
   année DATE,
   Id_label INT,
   PRIMARY KEY(Id_disque),
   FOREIGN KEY(Id_label) REFERENCES label(Id_label)
);

CREATE TABLE Asso_1(
   Id_disque INT,
   Id_UN_ENCULER_D_UTILISATEUR INT,
   PRIMARY KEY(Id_disque, Id_UN_ENCULER_D_UTILISATEUR),
   FOREIGN KEY(Id_disque) REFERENCES disque(Id_disque),
   FOREIGN KEY(Id_UN_ENCULER_D_UTILISATEUR) REFERENCES UN_ENCULER_D_UTILISATEUR(Id_UN_ENCULER_D_UTILISATEUR)
);
